# Generated by Django 5.1.2 on 2024-11-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0003_asyncjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="programme_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
