# Generated by Django 5.1.2 on 2024-11-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0004_alter_program_programme_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="household",
            name="history",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="history",
        ),
        migrations.AlterField(
            model_name="office",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
