# Generated by Django 5.1.2 on 2024-11-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0004_alter_program_programme_code"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryJob",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("country_workspace.asyncjob",),
        ),
    ]
